### ISSUE TITLE
ur code sucks

### ISSUE THREAD

**Issue by BrandonWLee** [mynameisivan/discord-bot#1]

**Comment by mynameisivan** [comment]
Can you provide some details on your issue? 

I'll assign a dev to follow up.

**Comment by BrandonWLee** [comment]
Precondition: 
N/A

Observe:
Code sucks
Expected;
Code doesn't suck

**Comment by mynameisivan** [comment]
@BrandonWLee can you try to reproduce this and see if this is still valid?

**Comment by BrandonWLee** [comment]
It's probably user error.

**Comment by mynameisivan** [comment]
Code looks alot better since we've moved to using a template, https://github.com/AnIdiotsGuide/guidebot.
