### ISSUE TITLE
[feature] .rank command

### ISSUE THREAD

**Issue by I-AM-STEVEe** [mynameisivan/discord-bot#19]
Summary:
Allow users set their ranks in a particular game

Usage:
`.rank [rank]` - sets current user's rank
`.rank @[username]` - returns another user's rank
`.ranks` - returns list of ranks for current channel

Notes:
- Utilize common component to only allow command in certain channels
- Could be used by future component for making queues (create api to retrieve rank)
- hardcode available ranks for now
- Use https://discordjs.guide/sequelize/#installing-and-using-sequelize as guide for data storage
- Or just use enmap; https://enmap.evie.dev/complete-examples/points

**Comment by mynameisivan** [comment]
For the usage documentation, we need to make it clear the to user that there are two usages of `.rank`:

```
.rank [level|@user]   set rank for current user or get rank for a user
```

I like the rank idea, maybe we can do top 10? 
```
.ranks 10
```
can show the next 10-20 offset. I think we should keep the list not too long.
