### ISSUE TITLE
misc is mispelled

### ISSUE THREAD

**Issue by mynameisivan** [mynameisivan/discord-bot#7]
when using help, the menu section is mispelled,

```
= Command List =

[Use .help <commandname> for details]
​
== Miscelaneous ==
.gif     :: Display a random gif
.mylevel :: Tells you your permission level for the current message location.
.ping    :: It like... Pings. Then Pongs. And it's not Ping Pong.
.stonks  :: Stonks only go up
```

**actual:**
"Miscelaneous"

**expected:**
"Miscellaneous"

**Comment by BrandonWLee** [comment]
Let's have our intern who is joining us soon take this one

**Comment by andi-n** [comment]
i'll make sure to tell you i'm stuck on this during next standup

**Comment by BrandonWLee** [comment]
Here's your welcoming gift @andi-n

**Comment by mynameisivan** [comment]
where are we on this? what are the next steps

**Comment by andi-n** [comment]
i clone repo soon

**Comment by BrandonWLee** [comment]
When do we expect this to be done? @andi-n

**Comment by BrandonWLee** [comment]
> i clone repo soon
hmm

**Comment by mynameisivan** [comment]
> > i clone repo soon
> 
> hmm

Maybe no return offer for this one...

**Comment by andi-n** [comment]
pull req now

**Comment by andi-n** [comment]
merged
